### ISSUE TITLE
Unasked for feedback on 'HTMX is the Future'

### ISSUE THREAD

**Issue by netaisllc** [quii/todo#1]
This is perhaps not be the best medium for messages of this type, but it might work out. Apologies in advance for any annoyance or hassle.

First, off **your post is excellent.** The care you put into writing it is obvious and sets it apart from 99% of all other dev-oriented content.  At least one reader - me - appreciates it and salutes you.

I should admit that I was already an HTMX believer before I came across your piece. What follows are editorial "ideas" aimed at sort of bolstering your post against the (willful?) misinterpretation by the unconvinced. (Or perhaps they are just the youthful.)

1. Consider explicitly saying "SPA, the client code" here:

![Screen Shot 2023-05-06 at 1 40 17 PM](https://user-images.githubusercontent.com/1242423/236646238-1e1b51f2-3646-42e8-b8be-6e05c38a9a91.png)

My rationale here is I've read many, many comments to Carson's web content that convince me there are a fair number of devs who actually are not grokking the important point you're making here.  Perhaps JSON data apis are all they know.  A connect-the-dots explicit approach may help them.

2. Consider a sentence or two of context about what the predominant app-arch pattern was back then.

![Screen Shot 2023-05-06 at 1 40 38 PM](https://user-images.githubusercontent.com/1242423/236646344-6f2f93ed-d790-4897-8132-2c10093f31c2.png)

This is an excellent call-out. ( BTWI actually had watched the podcast before I read your post. But the sum total of my Go knowledge is one, tiny PR merged to an OSS project I was using.) 

Younger readers may not get what CG meant when he described the idea of the browser as novel. _Why?_, they may wonder.

Perhaps a short note about what the prevailing pattern of apps back then - rather obese, highly app-specific clients - could improve this section.

3. Consider always explicitly saying "responds to HTTP requests with hypermedia".

![Screen Shot 2023-05-06 at 1 41 27 PM](https://user-images.githubusercontent.com/1242423/236646467-5dff7764-ba1d-4a1c-b04d-0632985471a4.png)

And also here:

![Screen Shot 2023-05-06 at 1 43 58 PM](https://user-images.githubusercontent.com/1242423/236646722-a2b68e27-90e2-4d42-a213-e1436fa7c2d5.png)

I like how you open this section and handle the reader's internal question (_Why is he mentioning Closure?_). 

I also hear another internal question of an "unconvinced" reader: _What's the big deal ? My (JSON data) api server responds to HTTP requests._

Which is true, but not the point, right?  It's _what_ the response is made of.  For my part I believe this has to be hammered on again and again as it seems to me to be fundamentally where the "ah ha" moment is.  And TBH it didn't come right away to me as I studied HTMX.

(Fo additional context, I'm also the idiot that tries to gently correct people when they claim, in the context of HTMX, "without any JavaScript", by suggesting they say "without any JavaScript written by me."  I am super impressed that you handled that on your own!)

4. Consider clarifying you mean on the _server_ side in regard to the first bullet. 

![Screen Shot 2023-05-06 at 1 42 49 PM](https://user-images.githubusercontent.com/1242423/236646639-cf6bcb0b-e099-458a-b5d0-e26cf4bfb3df.png)

Rationale: more of the same => be overtly clear for the reader who is interested but hasn't really mentally parsed out his/her app stack.

5. Consider emphasizing another aspect of brittleness: how clients get updates

![Screen Shot 2023-05-06 at 1 44 48 PM](https://user-images.githubusercontent.com/1242423/236646748-c1189642-6d03-4721-bd86-e787cb4771f3.png)

This section is already very strong, but I found myself wishing you'd touched on another "magical" aspect this architecture has over JSON apis:  the need for api versioning and client side updates melts away.

To me, this aspect and the general notion of elaborating an app over time _without having to worry very much about how each client will acquire the updates_ is way undervalued.  

DX, maintenance costs and app performance are certainly important, but isn't the point to write and deliver an app so good that thousands (millions?) of customers will want it?  In other words, why would we want to work in a way that success would impose a bigger and bigger problem (keeping everyone updated and implementing guards or handlers when somebody doesn't get updated)?

----

All right, here's one last chance to hate me - a random comment on the title of your site.

Early on in _The Elements of Style_  William Strunk lays out a set of "elementary rules"; the first of which deals with the possessive singular:

![Screen Shot 2023-05-06 at 2 19 18 PM](https://user-images.githubusercontent.com/1242423/236647033-96c01604-73c7-45c3-992c-7a226d062be8.png)

You are, of course, free to name your blog as you like. 100%. And you could usefully argue that American "rules" of style can go right back out the door, thank you very much.

But if you're writing about HTMX, I suspect you are comfortable pushing back on the way everybody else does it, and most everybody else pluralizes in way that conflicts with Strunk's advice.

Keep writing great posts, Chris. It helps us all.

**Comment by quii** [comment]
Hi Kevin!

I'm thrilled you liked the article and thank you very much for the kind words and feedback. I really appreciate you taking the time to write this. I took onboard _most_ of the things you said, the article will be updated shortly
